name: Pull Request

on:
  pull_request:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install Dependencies
        run: pnpm install

      - name: Biome CI
        run: pnpm exec biome ci .

      - name: Typecheck
        run: pnpm exec tsc --noEmit

      - name: Init docker
        run: docker compose up -d --wait

      - name: Test
        run: pnpm test:ci

      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
